Casgem_BigData/Casgem_BigData/Controllers/DefaultController.cs
using Casgem_BigData.Dal.Entities;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;

namespace Casgem_BigData.Controllers
{
    public class DefaultController : Controller
    {
        private readonly string connectionString = "server =LAPTOP-DMD5S6B7; initial Catalog=CARPLATES; integrated security=true";
        public ActionResult MarkayaGoreArama(string brand)
        {
            if (!string.IsNullOrEmpty(brand))
            {
                using (var connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    // Dapper ile sorguyu gerçekleştir
                    string query = "SELECT top 100 * FROM vw_PlatesBrand WHERE BRAND = @Brand";
                    var plates = connection.Query<Carplates>(query, new { Brand = brand }).ToList();

                    return View(plates);
                }
            }
            else
            {
                return View(new List<Carplates>());
            }
        }

        public int GetSedanPlateCount()
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand("SELECT * FROM vw_SedanPlateCount", connection);
                int sedanPlateCount = (int)command.ExecuteScalar();

                return sedanPlateCount;
            }
        }

        public int GetBenzinPlateCount()
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand("SELECT BenzinPlateCount FROM vw_BenzinPlateCount", connection);
                int benzinPlateCount = (int)command.ExecuteScalar();

                return benzinPlateCount;
            }
        }

        public int GetTotalCarCount()
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand("SELECT TotalCarCount FROM vw_TotalCarCount", connection);
                int totalCarCount = (int)command.ExecuteScalar();

                return totalCarCount;
            }
        }
        public int GetDuzPlateCount()
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand("SELECT DuzPlateCount FROM vw_DuzPlateCount", connection);
                int duzPlateCount = (int)command.ExecuteScalar();

                return duzPlateCount;
            }
        } 
        public int GetYariOtomatikPlateCount()
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand("SELECT YariOtomatikPlateCount FROM vw_YariOtomatikPlateCount", connection);
                int yariOtomatikPlateCount = (int)command.ExecuteScalar();

                return yariOtomatikPlateCount;
            }
        }

        public string GetMostCommonModel()
        {
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                SqlCommand command = new SqlCommand("SELECT TOP 1 MODEL FROM vw_MostCommonModel", connection);
                string enYaygınModel = (string)command.ExecuteScalar();

                return enYaygınModel;
            }
        }

    }



}

Casgem_BigData/Casgem_BigData/Controllers/IstatisliklerController.cs
using Casgem_BigData.Controllers;
using Microsoft.AspNetCore.Mvc;

public class IstatisliklerController : Controller
{
    private DefaultController defaultController = new DefaultController();

    public ActionResult Index()
    {
        int sedanPlateCount = defaultController.GetSedanPlateCount();
        int benzinPlateCount = defaultController.GetBenzinPlateCount();
        int totalCarCount = defaultController.GetTotalCarCount();
        int duzPlateCount = defaultController.GetDuzPlateCount();
        int yariOtomatikPlateCount = defaultController.GetYariOtomatikPlateCount();
        string enYayginModel = defaultController.GetMostCommonModel();

        ViewBag.SedanPlateCount = sedanPlateCount;
        ViewBag.BenzinPlateCount = benzinPlateCount;
        ViewBag.TotalCarCount = totalCarCount;
        ViewBag.DuzPlateCount = duzPlateCount;
        ViewBag.YariOtomatikPlateCount = yariOtomatikPlateCount;
        ViewBag.EnYayginModel = enYayginModel;

        return View();
    }
}

Casgem_BigData/Casgem_BigData/Views/Default/MarkayaGoreArama.cshtml
@model IEnumerable<Casgem_BigData.Dal.Entities.Carplates>
@{
    ViewData["Title"] = "MarkayaGoreArama";
    Layout = null;
}

<link rel="stylesheet" href="~/css/styles.css" />

<head>
<style>
    /* Tablo tasarımı */
    table {
        border-collapse: collapse;
        width: 100%;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ccc;
        padding: 8px;
    }

    th {
        background-color: #f2f2f2;
    }

    /* Form tasarımı */
    form {
        margin-bottom: 20px;
    }

    label {
        display: block;
        margin-bottom: 5px;
    }

    input[type="text"] {
        width: 200px;
        padding: 5px;
    }

    button {
        padding: 5px 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        cursor: pointer;
    }

    /* Arama Sonuçları başlığı */
    

        .container {
            display: flex;
            justify-content: center;
        }

        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
        }

        .header {
            background-color: #4CAF50;
            color: white;
            padding: 10px;
            display: flex;
            align-items: center;
        }

        .logo {
            font-size: 24px;
            margin: 0;
            padding: 0;
        }

        .navbar {
            flex-grow: 1;
            text-align: right;
        }

        .menu {
            list-style: none;
            padding: 0;
            margin: 0;
        }

            .menu li {
                display: inline-block;
                margin-left: 20px;
            }

            .menu a {
                text-decoration: none;
                color: white;
                font-size: 16px;
                padding: 5px 10px;
                border-radius: 5px;
            }

                .menu a:hover {
                    background-color: #4CAF50;
                }




</style>
</head>

<body>
    <header class="header">
        <nav class="navbar">
            <ul class="menu">
                <li><a href="/Default/MarkayaGoreArama/">Ara</a></li>
                <li><a href="@Url.Action("Index", "Istatislikler")">İstatistik</a></li>
            </ul>
        </nav>
    </header>
    <br/> <br/> <br/>
<div class="container">
<form method="post" action="@Url.Action("MarkayaGoreArama", "Default")">
    <label for="brandInput">Marka:</label>
    <input type="text" id="brandInput" name="brand" />
    <button type="submit">Ara</button>
</form>
    </div>
@if (Model != null)
{
    <h3>Arama Sonuçları:</h3>
    <table>
        <thead>
            <tr>
                <th>Plaka</th>
                <th>Marka</th>
                <th>Seri</th>
                <th>Model</th>
                <th>Yıl</th>
                <th>Yakıt</th>
                <th>Vites</th>
                <th>Motor Hacmi</th>
                <th>Motor Gücü</th>
                <th>Renk</th>
                <th>Kasa Tipi</th>
                <th>Lisans Tarihi</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var plate in Model)
            {
                <tr>
                    <td>@plate.PLATE</td>
                    <td>@plate.BRAND</td>
                    <td>@plate.MODEL</td>
                    <td>@plate.TITLE</td>
                    <td>@plate.YEAR_</td>
                    <td>@plate.FUEL</td>
                    <td>@plate.SHIFTTYPE</td>
                    <td>@plate.MOTORVOLUME</td>
                    <td>@plate.MOTORPOWER</td>
                    <td>@plate.COLOR</td>
                    <td>@plate.CASETYPE</td>
                    <td>@plate.LICENCEDATE</td>
                </tr>
            }
        </tbody>
    </table>
}

</body>

Casgem_BigData/Casgem_BigData/Views/Istatislikler/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>İstatistikler</title>
    <style>
        <style >
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f1f1f1;
        }

        /* Kart stili */
        .card {
            display: inline-block;
            width: 200px;
            height: 150px;
            padding: 10px;
            margin: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

            /* Kart başlık stili */
            .card h3 {
                font-size: 16px;
                color: #333;
            }

            /* Kart içerik stili */
            .card p {
                font-size: 20px;
                color: #007bff;
                margin-top: 5px;
            }

        .container {
            width: 50%; /* Sayfa genişliğinin yüzde 80'ine ayarlandı */
            margin: 0 auto; /* Yatayda merkezlemek için otomatik marj ekledik */
        }


    </style>
</head>
<body>
    <h1 style="text-align: center;">İstatistikler</h1>
    <div class="container">
    <div style="text-align: center;" class="card">
        <h3>Sedan Araç Sayısı:</h3>
        <p>@ViewBag.SedanPlateCount</p>
    </div>
    <div style="text-align: center;" class="card">
        <h3>Benzinli Araç Sayısı:</h3>
        <p>@ViewBag.BenzinPlateCount</p>
    </div>
    <div style="text-align: center;" class="card">
        <h3>Toplam Araç Sayısı:</h3>
        <p>@ViewBag.TotalCarCount</p>
    </div>
    <br/> <br/>
    <div style="text-align: center;" class="card">
        <h3>Düz Vitesli Araç Sayısı:</h3>
        <p>@ViewBag.DuzPlateCount</p>
    </div>
    <div style="text-align: center;" class="card">
        <h3>Yarı Otomatik Araç Sayısı:</h3>
        <p>@ViewBag.YariOtomatikPlateCount</p>
    </div>
    <div style="text-align: center;" class="card">
        <h3>En Çok Bulunan Model:</h3>
        <p>@ViewBag.EnYayginModel</p>
    </div>
    </div>
</body>
</html>

Casgem_BigData/Casgem_BigData/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Casgem_BigData</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Casgem_BigData.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Casgem_BigData</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Casgem_BigData - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Casgem_BigData/Casgem_BigData/Views/Shared/_İstatistikLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>BİG DATA</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="">
    <meta name="author" content="Phoenixcoded" />
    <!-- Favicon icon -->
    <link rel="icon" href="~/Template/template\flat-able-lite\dist\assets/images/favicon.ico" type="image/x-icon">

    <!-- prism css -->
    <link rel="stylesheet" href="~/Template/template\flat-able-lite\dist\assets/css/plugins/prism-coy.css">
    <!-- vendor css -->
    <link rel="stylesheet" href="~/Template/template\flat-able-lite\dist\assets/css/style.css">



</head>

<body>
    <!-- [ Pre-loader ] start -->
    <!-- [ Pre-loader ] End -->
    <!-- [ navigation menu ] start -->
    <!-- [ navigation menu ] end -->
    <!-- [ Header ] start -->
    <header class="navbar pcoded-header navbar-expand-lg navbar-light header-dark">
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                
                <li class="nav-item">
                    <div class="dropdown">
                        <a class="dropdown-toggle h-drop" href="#" data-toggle="Ara">
                            Ara
                        </a>
                    </div>
                </li>
                <li class="nav-item">
                    <div class="dropdown mega-menu">
                        <a class="dropdown-toggle h-drop" href="#" data-toggle="İstatistikler">
                            İstatistik
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </header>
    <!-- [ Header ] end -->
    <!-- [ Main Content ] start -->
    <div>
        @RenderBody() 
     </div>
    <!-- [ Main Content ] end -->
    <!-- Warning Section start -->
    <!-- Older IE warning message -->
    <!-- Warning Section Ends -->
    <!-- Required Js -->
    <script src="~/Template/template/flat-able-lite/dist/assets/js/vendor-all.min.js"></script>
    <script src="~/Template/template/flat-able-lite/dist/assets/js/plugins/bootstrap.min.js"></script>
    <script src="~/Template/template/flat-able-lite/dist/assets/js/pcoded.min.js"></script>

    <!-- prism Js -->
    <script src="~/Template/template\flat-able-lite\dist\assets/js/plugins/prism.js"></script>
</body>

</html>